data:
  root: '~/datasets/reid'
  sources: ['market1501']
  targets: ['occluded_reid']
  height: 384
  width: 128
  transforms: ['rc', 're']

model:
  name: 'bpbreid'
  load_weights: 'pretrained_models/'
  load_config: True
  bpbreid:
    mask_filtering_training: False
    mask_filtering_testing: True
    learnable_attention_enabled: True
    backbone: 'hrnet32'
    test_embeddings: ['bn_foreg', 'parts']
    masks:
      dir: 'pifpaf_maskrcnn_filtering'
      preprocess: 'five_v'

test:
  evaluate: True
  batch_size: 64
  visrank: True
