data:
  root: '/huangsiteng/ReID_datasets'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  transforms: [ 'rf', 'rc', 're' ]
  norm_mean: [ 0.5, 0.5, 0.5 ]
  norm_std: [ 0.5, 0.5, 0.5 ]

model:
  name: 'clipreid'
#  load_weights: '/huangsiteng/bpbreid/logs/605198288/2024_01_15_09_13_53_13S09b8384c-82fd-4510-9934-d56a212ea014model/job-605198288_60_model.pth.tar'
  load_weights: '/huangsiteng/bpbreid/logs/657212792/2024_01_18_09_10_01_10S9bd174a4-85d4-4611-9a96-458615b4881dmodel/job-657212792_60_model.pth.tar'
  load_config: True
  bpbreid:
    mask_filtering_training: False
    mask_filtering_testing: True
    learnable_attention_enabled: True
    backbone: 'ViT-B-16'
    test_embeddings: ['globl']
    masks:
      dir: 'pifpaf_maskrcnn_filtering'
      preprocess: 'five_v'
    stride_size: [ 16, 16 ]
    upsample: True

test:
  evaluate: True
  batch_size: 64
  visrank: True
