data:
  root: '/huangsiteng/ReID_datasets/dukemtmcreid'
  sources: ['occluded_duke']
  targets: ['occluded_duke']
  height: 256
  width: 128
  transforms: ['rc', 're']
  norm_mean: [ 0.5, 0.5, 0.5 ]
  norm_std: [ 0.5, 0.5, 0.5 ]

model:
  name: 'clipreid_bpb'
  bpbreid:
    mask_filtering_training: False
    mask_filtering_testing: True
    learnable_attention_enabled: True
    backbone: 'ViT-B-16'
    test_embeddings: ['bn_globl', 'bn_parts']
    masks:
      dir: 'pifpaf_maskrcnn_filtering'
      preprocess: 'five_v'
    stride_size: [12, 12]
    upsample: True
    #SIE_CAMERA: True
    SIE_COE : 0.0

loss:
  name: 'part_based'
  part_based:
    name: 'part_averaged_triplet_loss'
    ppl: 'cl'
    weights:  # SOTA weights for GiLt loss
      globl:
        id: 1.
        tr: 1.
      foreg:
        id: 0.
        tr: 0.
      conct:
        id: 1.
        tr: 1.
      parts:
        id: 0.
        tr: 0.
      pixls:
        ce: 0.35

train:
  max_epoch: 60
  batch_size: 64
  lr: 0.00004
  weight_decay: 0.0005
  stepsize: [ 30, 50 ]
  seed: 1234
  staged_lr: True
  #  base_lr_mult: 0.1
  new_layers: [ 'image_encoder' ]

test:
  evaluate: False
  batch_size: 64
  visrank: True
