data:
  root: '/huangsiteng/ReID_datasets/dukemtmcreid'
  sources: ['occluded_duke']
  targets: ['occluded_duke']
  height: 256
  width: 128
  transforms: ['rc', 're']

model:
  name: 'clipreid'
  bpbreid:
    mask_filtering_training: False
    mask_filtering_testing: True
    learnable_attention_enabled: True
    backbone: 'ViT-B-16'
    test_embeddings: ['bn_foreg', 'parts']
    masks:
      dir: 'pifpaf_maskrcnn_filtering'
      preprocess: 'eight'
    stride_size: [16, 16]
    upsample: True
    #SIE_CAMERA: True
    # SIE_COE : 1.0

loss:
  name: 'part_based'
  part_based:
    name: 'part_averaged_triplet_loss'
    ppl: 'cl'
    weights:  # SOTA weights for GiLt loss
      globl:
        id: 1.
        tr: 0.
      foreg:
        id: 1.
        tr: 0.
      conct:
        id: 1.
        tr: 0.
      parts:
        id: 0.
        tr: 1.
      pixls:
        ce: 5.

train:
  batch_size: 64

test:
  evaluate: False
  batch_size: 64
  visrank: True
